# Generated by Django 5.2 on 2025-09-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='designationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='employeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('deparment', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('joiningDate', models.DateField(auto_now_add=True, null=True)),
                ('sex', models.CharField(max_length=10, null=True)),
                ('bloodGroup', models.CharField(max_length=10, null=True)),
                ('basicSalary', models.IntegerField()),
            ],
        ),
    ]
